language: ruby

rvm:
  - 2.2.5
  - 2.3.1
  - 2.4
  - jruby-9.1.5.0

gemfile:
- gemfiles/sidekiq_4.0.gemfile
- gemfiles/sidekiq_4.1.gemfile
- gemfiles/sidekiq_4.2.gemfile
- gemfiles/sidekiq_5.0.gemfile
- gemfiles/sidekiq_master.gemfile

services:
  - redis-server
